---
- hosts: localhost
  # connection: local
  tasks:
    - name: Generate kube-proxy
      become: true
      shell: |
        KUBERNETES_PUBLIC_ADDRESS=$(cat /tmp/lb-address)

        kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=../1_ca/ca.pem \
        --embed-certs=true \
        --server=https://${KUBERNETES_PUBLIC_ADDRESS}:6443 \
        --kubeconfig=kube-proxy.kubeconfig

        kubectl config set-credentials system:kube-proxy \
          --client-certificate=../1_ca/kube-proxy.pem \
          --client-key=k../1_ca/ube-proxy-key.pem \
          --embed-certs=true \
          --kubeconfig=kube-proxy.kubeconfig

        kubectl config set-context default \
          --cluster=kubernetes-the-hard-way \
          --user=system:kube-proxy \
          --kubeconfig=kube-proxy.kubeconfig

        kubectl config use-context default --kubeconfig=kube-proxy.kubeconfig
