---
- hosts: kube_minions
  tasks:
    - name: Copy worker-0.kubeconfig kube-proxy.kubeconfig to minions 
      become: true
      copy:
        src: "{{ item }}"
        dest: "/root/"
      with_items:
        - ../1_ca/worker-0.kubeconfig
        - ../1_ca/kube-proxy.kubeconfig   

- hosts: kube_master
  tasks:
    - name: Copy admin.kubeconfig kube-controller-manager.kubeconfig kube-scheduler.kubeconfig to minions
      become: true
      copy:
        src: "{{ item }}"
        dest: "/root/"
      with_items:
        - ../1_ca/admin.kubeconfig
        - ../1_ca/kube-controller-manager.kubeconfig 
        - ../1_ca/kube-scheduler.kubeconfig      
