---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create admin.pem & admin-key.pem
      # become: true
      shell: |
        cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes \
        admin-csr.json | cfssljson -bare admin
