---
- hosts: 127.0.0.1
  tasks:
    
    - name: Create worker-0-csr.json
      become: true
      copy:
        dest: worker-0-csr.json
        content: '{"CN":"system:node:worker-0","key":{"algo":"rsa","size":2048},"names":[{"C":"US","L":"Portland","O":"system:nodes","OU":"Kubernetes The Hard Way","ST":"Oregon"}]}'

    - name: Create worker-*.pem & worker-*-key.pem for kubelet
      # become: true
      shell: |
        EXTERNAL_IP=$(cat /tmp/worker-public)

        INTERNAL_IP=$(cat /tmp/worker-private)

        cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -hostname=worker-0,${EXTERNAL_IP},${INTERNAL_IP} \
        -profile=kubernetes \
        worker-0-csr.json | cfssljson -bare worker-0
