---
- hosts: kube_master
  tasks:
    - name: Create kube-controller-manager.pem &kube-controller-manager-key.pem
      # become: true      
      shell:
        cmd: |        
          cat > kube-controller-manager-csr.json << EOF
          {
            "CN": "system:kube-controller-manager",
            "key": {
              "algo": "rsa",
              "size": 2048
            },
            "names": [
              {
                "C": "US",
                "L": "Portland",
                "O": "system:kube-controller-manager",
                "OU": "Kubernetes The Hard Way",
                "ST": "Oregon"
              }
            ]
          }
          EOF        

    - name: Generate certs
      shell: |
        cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes \
        kube-controller-manager-csr.json | cfssljson -bare kube-controller-manager                     
        
