---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create kube-controller-manager.pem &kube-controller-manager-key.pem
      become: true
      shell: |
        cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-controller-manager-csr.json | cfssljson -bare kube-controller-manager
