---
- hosts: all
  become: true
  tasks:
  
    - name: Copy the file
      copy:
        src: "/etc/ansible/hosts"
        dest: "/root/machan.txt"

    - name: Create the ca.pem & ca-key.pem
      become: true
      shell: |
        cfssl gencert -initca ca-csr.json | cfssljson -bare ca       