---
- hosts: 127.0.0.1
  connection: local
  tasks:
    
    - name: Create admin.pem & admin-key.pem
      # become: true
      shell: |
        EXTERNAL_IP=$(gcloud compute instances describe worker-0 \
        --format 'value(networkInterfaces[0].accessConfigs[0].natIP)')

        INTERNAL_IP=$(gcloud compute instances describe worker-0 \
        --format 'value(networkInterfaces[0].networkIP)')

        cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -hostname=worker-0,${EXTERNAL_IP},${INTERNAL_IP} \
        -profile=kubernetes \
        worker-0-csr.json | cfssljson -bare worker-0
