---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Download cfssl and cfssljson
      get_url:
        url: "{{ item }}"
        dest: /tmp
      with_items:
        - https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssl
        - https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssljson

    - name: Copying cfssl & cfssljson to /usr/local/bin/
      become: true
      copy: src=/tmp/{{ item }} dest=/usr/local/bin/
      with_items:
        - cfssl
        - cfssljson

    - name: Changing perm of "cfssl", adding "+x"
      file:
        dest: "{{ item }}"
        mode: +x  
      with_items:
        - /usr/local/bin/cfssl 
        - /usr/local/bin/cfssljson             

- hosts: kube_master
  # connection: local
  tasks:
    - name: Download cfssl and cfssljson
      get_url:
        url: "{{ item }}"
        dest: /tmp
      with_items:
        - https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssl
        - https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssljson

    - name: Copying cfssl & cfssljson to /usr/local/bin/
      become: true
      copy: src=/tmp/{{ item }} dest=/usr/local/bin/
      with_items:
        - cfssl
        - cfssljson

    - name: Changing perm of "cfssl", adding "+x"
      file:
        dest: "{{ item }}"
        mode: +x  
      with_items:
        - /usr/local/bin/cfssl 
        - /usr/local/bin/cfssljson 