---
- hosts: localhost
  # connection: local
  tasks:
    - name: Generate kubeconfig for each worker node
      become: true
      shell: |
        KUBERNETES_PUBLIC_ADDRESS=$(cat /tmp/lb-address)

        kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://${KUBERNETES_PUBLIC_ADDRESS}:6443 \
        --kubeconfig=worker-0.kubeconfig

        kubectl config set-credentials system:node:worker-0 \
        --client-certificate=worker-0.pem \
        --client-key=worker-0-key.pem \
        --embed-certs=true \
        --kubeconfig=worker-0.kubeconfig

        kubectl config set-context default \
        --cluster=kubernetes-the-hard-way \
        --user=system:node:worker-0 \
        --kubeconfig=worker-0.kubeconfig

        kubectl config use-context default --kubeconfig=worker-0.kubeconfig
