---
- hosts: 127.0.0.1
  tasks:

    - name: Create admin-csr.json
      become: true
      copy:
        dest: admin-csr.json
        content: '{"CN":"admin","key":{"algo":"rsa","size":2048},"names":[{"C":"US","L":"Portland","O":"system:masters","OU":"Kubernetes The Hard Way","ST":"Oregon"}]}'

    - name: Create admin.pem & admin-key.pem
      # become: true
      shell: |
        cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes \
        admin-csr.json | cfssljson -bare admin
