---
- hosts: kube_master
  tasks:

    - name: Update the libraries
      become: true
      apt:
        update_cache: yes

    - name: Install a basic web server to handle HTTP health checks
      become: true
      apt:
        name: nginx
        state: present

    - name: Create kubernetes.default.svc.cluster.local
      become: true
      shell: |
        cat > kubernetes.default.svc.cluster.local <<EOF
        server {
          listen      80;
          server_name kubernetes.default.svc.cluster.local;

          location /healthz {
            proxy_pass                    https://127.0.0.1:6443/healthz;
            proxy_ssl_trusted_certificate /var/lib/kubernetes/ca.pem;
          }
        }
        EOF

        sudo mv kubernetes.default.svc.cluster.local \
        /etc/nginx/sites-available/kubernetes.default.svc.cluster.local

        sudo ln -s /etc/nginx/sites-available/kubernetes.default.svc.cluster.local /etc/nginx/sites-enabled/

    - pause:
        seconds: 10            

    - name: Start the Controller Services      
      become: true
      systemd:
        state: restarted
        name: nginx
        daemon_reload: yes   

    - name: Enable the Controller Services      
      become: true
      systemd:
        name: nginx
        daemon_reload: yes            
      